poc/funcionarios_crud/apps/urls.py
from django.urls import include, path
from django.contrib import admin

from funcionarios import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('books_cbv/', include('books_cbv.urls', namespace='books_cbv')),
    path('books_fbv/', include('books_fbv.urls', namespace='books_fbv')),
    path('books_fbv_user/', include('books_fbv_user.urls', namespace='books_fbv_user')),
    path('main/', views.main),
    path('', views.home),
]

poc/funcionarios_crud/books_cbv/urls.py
from django.urls import path

from . import views

app_name = 'books_cbv'

urlpatterns = [
  path('', views.BookList.as_view(), name='book_list'),
  path('new', views.BookCreate.as_view(), name='book_new'),
  path('edit/<int:pk>', views.BookUpdate.as_view(), name='book_edit'),
  path('delete/<int:pk>', views.BookDelete.as_view(), name='book_delete'),
]

poc/funcionarios_crud/books_fbv/urls.py
from django.urls import path

from books_fbv import views

app_name = 'books_fbv'

urlpatterns = [
  path('', views.book_list, name='book_list'),
  path('new', views.book_create, name='book_new'),
  path('edit/<int:pk>', views.book_update, name='book_edit'),
  path('delete/<int:pk>', views.book_delete, name='book_delete'),
]

poc/funcionarios_crud/books_fbv_user/urls.py
from django.urls import path

from . import views

app_name = 'books_fbv_user'

urlpatterns = [
  path('', views.book_list, name='book_list'),
  path('new', views.book_create, name='book_new'),
  path('edit/<int:pk>', views.book_update, name='book_edit'),
  path('delete/<int:pk>', views.book_delete, name='book_delete'),
]

poc/funcionarios_crud/books_cbv/models.py
from django.db import models
from django.urls import reverse


class Book(models.Model):
    name = models.CharField(max_length=200)
    pages = models.IntegerField()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('books_cbv:book_edit', kwargs={'pk': self.pk})

poc/funcionarios_crud/books_fbv/models.py
from django.db import models
from django.urls import reverse


class Book(models.Model):
    name = models.CharField(max_length=200)
    pages = models.IntegerField()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('books_fbv:book_edit', kwargs={'pk': self.pk})

poc/funcionarios_crud/books_fbv_user/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings

class Book(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    pages = models.IntegerField()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('books_fbv_user:book_edit', kwargs={'pk': self.pk})

poc/funcionarios_crud/funcionarios/models.py
from django.db import models

# Create your models here.

poc/funcionarios_crud/apps/views.py
from django.shortcuts import render

poc/funcionarios_crud/books_cbv/views.py
from django.http import HttpResponse
from django.views.generic import TemplateView,ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy

from books_cbv.models import Book

class BookList(ListView):
    model = Book

class BookCreate(CreateView):
    model = Book
    fields = ['name', 'pages']
    success_url = reverse_lazy('books_cbv:book_list')

class BookUpdate(UpdateView):
    model = Book
    fields = ['name', 'pages']
    success_url = reverse_lazy('books_cbv:book_list')

class BookDelete(DeleteView):
    model = Book
    success_url = reverse_lazy('books_cbv:book_list')

poc/funcionarios_crud/books_fbv/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.forms import ModelForm

from books_fbv.models import Book

class BookForm(ModelForm):
    class Meta:
        model = Book
        fields = ['name', 'pages']

def book_list(request, template_name='books_fbv/book_list.html'):
    book = Book.objects.all()
    data = {}
    data['object_list'] = book
    return render(request, template_name, data)

def book_create(request, template_name='books_fbv/book_form.html'):
    form = BookForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('books_fbv:book_list')
    return render(request, template_name, {'form':form})

def book_update(request, pk, template_name='books_fbv/book_form.html'):
    book= get_object_or_404(Book, pk=pk)
    form = BookForm(request.POST or None, instance=book)
    if form.is_valid():
        form.save()
        return redirect('books_fbv:book_list')
    return render(request, template_name, {'form':form})

def book_delete(request, pk, template_name='books_fbv/book_confirm_delete.html'):
    book= get_object_or_404(Book, pk=pk)    
    if request.method=='POST':
        book.delete()
        return redirect('books_fbv:book_list')
    return render(request, template_name, {'object':book})

poc/funcionarios_crud/books_fbv_user/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.forms import ModelForm

from books_fbv_user.models import Book

class BookForm(ModelForm):
    class Meta:
        model = Book
        fields = ['name', 'pages']

@login_required
def book_list(request, template_name='books_fbv_user/book_list.html'):
    if request.user.is_superuser:
        book = Book.objects.all()
    else:
        book = Book.objects.filter(user=request.user)
    data = {}
    data['object_list'] = book
    return render(request, template_name, data)

@login_required
def book_create(request, template_name='books_fbv_user/book_form.html'):
    form = BookForm(request.POST or None)
    if form.is_valid():
        book = form.save(commit=False)
        book.user = request.user
        book.save()
        return redirect('books_fbv_user:book_list')
    return render(request, template_name, {'form':form})

@login_required
def book_update(request, pk, template_name='books_fbv_user/book_form.html'):
    if request.user.is_superuser:
        book= get_object_or_404(Book, pk=pk)
    else:
        book= get_object_or_404(Book, pk=pk, user=request.user)
    form = BookForm(request.POST or None, instance=book)
    if form.is_valid():
        form.save()
        return redirect('books_fbv_user:book_list')
    return render(request, template_name, {'form':form})

@login_required
def book_delete(request, pk, template_name='books_fbv_user/book_confirm_delete.html'):
    if request.user.is_superuser:
        book= get_object_or_404(Book, pk=pk)
    else:
        book= get_object_or_404(Book, pk=pk, user=request.user)
    if request.method=='POST':
        book.delete()
        return redirect('books_fbv_user:book_list')
    return render(request, template_name, {'object':book})

poc/funcionarios_crud/funcionarios/views.py
from django.shortcuts import render

def home(request):
    return render(request, "home.html")

def main(request):
    return render(request, "main.html")

poc/funcionarios_crud/books_cbv/templates/books_cbv/book_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<h2><a href="{% url 'books_cbv:book_list' %}">Books CBV</a>: Delete?</h2>

<form method="post">{% csrf_token %}
    Are you sure you want to delete "{{ object }}" ?<br>
    <input type="submit" value="Delete" />
</form>

{% endblock %}

poc/funcionarios_crud/books_cbv/templates/books_cbv/book_form.html
{% extends "base.html" %}

{% block content %}

<h2><a href="{% url 'books_cbv:book_list' %}">Books CBV</a>: Edit</h2>

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

{% endblock %}

poc/funcionarios_crud/books_cbv/templates/books_cbv/book_list.html
{% extends "base.html" %}

{% block content %}

<h2><a href="{% url 'books_cbv:book_list' %}">Books CBV</a></h2>

<ul>
    {% for book in object_list %}
    <li>{{ book.name }}  ({{ book.pages }} Pages)
    <a href="{% url 'books_cbv:book_edit' book.id %}">edit</a>
    <a href="{% url 'books_cbv:book_delete' book.id %}">delete</a>
    </li>
    {% endfor %}
</ul>

<a href="{% url 'books_cbv:book_new' %}">New</a>

{% endblock %}

poc/funcionarios_crud/books_fbv/templates/books_fbv/book_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<h2><a href="{% url 'books_fbv:book_list' %}">Books FBV</a>: Delete?</h2>

<form method="post">{% csrf_token %}
    Are you sure you want to delete "{{ object }}" ?<br/>
    <input type="submit" value="Delete" />
</form>

{% endblock %}

poc/funcionarios_crud/books_fbv/templates/books_fbv/book_form.html
{% extends "base.html" %}

{% block content %}

<h2><a href="{% url 'books_fbv:book_list' %}">Books FBV</a>: Edit</h2>

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

{% endblock %}

poc/funcionarios_crud/books_fbv/templates/books_fbv/book_list.html
{% extends "base.html" %}

{% block content %}

<h2><a href="{% url 'books_fbv:book_list' %}">Books FBV</a></h2>

<ul>
    {% for book in object_list %}
    <li>{{ book.name }}  ({{ book.pages }} Pages)
    <a href="{% url 'books_fbv:book_edit' book.id %}">edit</a>
    <a href="{% url 'books_fbv:book_delete' book.id %}">delete</a>
    </li>
    {% endfor %}
</ul>

<a href="{% url 'books_fbv:book_new' %}">New</a>

{% endblock %}

poc/funcionarios_crud/books_fbv_user/templates/books_fbv_user/book_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<h2><a href="{% url 'books_fbv_user:book_list' %}">Books FBV User</a>: Delete?</h2>

<form method="post">{% csrf_token %}
    Are you sure you want to delete "{{ object }}" ?<br/>
    <input type="submit" value="Delete" />
</form>

{% endblock %}

poc/funcionarios_crud/books_fbv_user/templates/books_fbv_user/book_form.html
{% extends "base.html" %}

{% block content %}

<h2><a href="{% url 'books_fbv_user:book_list' %}">Books FBV User</a>: Edit</h2>

<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>

{% endblock %}

poc/funcionarios_crud/books_fbv_user/templates/books_fbv_user/book_list.html
{% extends "base.html" %}

{% block content %}

<h2><a href="{% url 'books_fbv_user:book_list' %}">Books FBV User</a></h2>

<ul>
    {% for book in object_list %}
    <li>{{ book.name }}  ({{ book.pages }} Pages)
    <a href="{% url 'books_fbv_user:book_edit' book.id %}">edit</a>
    <a href="{% url 'books_fbv_user:book_delete' book.id %}">delete</a>
    </li>
    {% endfor %}
</ul>

<a href="{% url 'books_fbv_user:book_new' %}">New</a>

{% endblock %}

poc/funcionarios_crud/funcionarios/templates/base.html
{% load static %}

<html>
<head>
    <title></title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
    <div id="header">
        <h1><a href="/">Django CRUD Example</a></h1>
    </div><!-- header -->
    <div id="content">
        {% block content %}
        {% endblock %}
    </div><!-- content -->
</body>
</html>

poc/funcionarios_crud/funcionarios/templates/home.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Login</title>
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1,  shrink-to-fit=no"
    />
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
      integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf"
      crossorigin="anonymous"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Dosis&display=swap"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="../static/css/bootstrap.min.css" type="text/css" />
    <link rel="stylesheet" type="text/css" href="../static/css/style.css" />
  </head>
  <body class="loginpage">
    <div class="card text-center" id="containerlogin">
      <div>
        <img src="../static/img/logonecto.svg" class="img-fluid" alt="logo Necto" style="width: 150px; height: 60px;">
      </div>
      <div class="card-body">
        <label class="pb-4 font-weight-bold">LOGIN</label>
        <form>
          <div class="form-group">
            <input type="text" class="form-control" id="formGroupExampleInput" placeholder="Usuario">
          </div>
          <div class="form-group">
            <input type="password" class="form-control" id="formGroupExampleInput2" placeholder="Senha">
          </div>
          <a href="main" class="btn btn-login">Entrar</a>
        </form>
      </div>
    </div>
    
    <script src="../static/js/jquery-3.4.1.min.js"></script>
    <script src="../static/js/popper.min.js"></script>
    <script src="../static/js/bootstrap.min.js"></script>
    <script src="../static/js/main.js"></script>
    {% block content %}
    {% endblock %}
  </body>
</html>

poc/funcionarios_crud/funcionarios/templates/main.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Painel</title>
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1,  shrink-to-fit=no"
    />
    <link
      rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
      integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf"
      crossorigin="anonymous"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Dosis&display=swap"
      rel="stylesheet"
    />
    <link rel="stylesheet" href="../static/css/bootstrap.min.css" type="text/css" />
    <link rel="stylesheet" type="text/css" media="screen" href="../static/css/style.css" />
  </head>
  <body class="body">
    <div class="bg-dark">
      <img src="../static/img/logonectobranco.svg" class="img-fluid mt-2 ml-2 pb-2" alt="logo Necto" style="width: 160px; height: 80;">
      <div class="btn-group float-right pt-1 mr-3">
        <button type="button" class="btn btn-secondary dropdown-toggle btnrounded mt-3" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
         Nome
        </button>
        <div class="dropdown-menu">
          <a class="dropdown-item" href="#">Alterar</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="index.html">Sair</a>
        </div>
      </div>
      <a href="/books_cbv/" class="btn btn-secondary ml-5 tamanho">Projetos</a>
      <a href="/books_fbv/" class="btn btn-secondary tamanho ml-5">Funcionários</a>
      <a href="/books_fbv/" class="btn btn-secondary tamanho ml-5">Tarefas</a>
    </div>
   
      <div>

      </div>
    
    <script src="../static/js/jquery-3.4.1.min.js"></script>
    <script src="../static/js/popper.min.js"></script>
    <script src="../static/js/bootstrap.min.js"></script>
    <script src="../static/js/main.js"></script>
    {% block content %}
    {% endblock %}
  </body>
</html>